repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        args: ["src"]
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: isort
        language: system
        args: ["src"]
    -   id: flake8
        name: flake8
        entry: flake8
        args: ["src"]
        language: python
        types: [python]
